Controllers/CertificationController.cs
using certificationRegister.Models;
using certificationRegister.Repositories;
using certificationRegister.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace certificationRegister.Controllers
{
    [Authorize]
    public class CertificationController : Controller
    {
        private readonly IRepository<Certification> _bd;

        public CertificationController(IRepository<Certification> certification)
        {
            _bd = certification;
        }
        public IActionResult Index()
        {
            var model = _bd.AllCertification();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CertificationCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var cert = new Certification()
                {
                    sigle = model.sigle.ToUpper(),
                    libelle = model.libelle
                };
                _bd.Create(cert);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _bd.GetCertification(id);
            if (model != null)
            {
                var cert = new CertificationEditViewModel()
                {
                    sigle = model.sigle,
                    libelle = model.libelle,
                    certificationId = model.certificationId
                };
                return View(cert);
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public IActionResult Edit(CertificationEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var cert = _bd.GetCertification(model.certificationId);
                if (cert != null)
                {
                    cert.sigle = model.sigle;
                    cert.libelle = model.libelle;
                    _bd.Update(cert);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = _bd.GetCertification(id);
            if (model != null)
            {
                var cert = new CertificationEditViewModel()
                {
                    sigle = model.sigle,
                    libelle = model.libelle,
                    certificationId = model.certificationId
                };
                return View(cert);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(CertificationEditViewModel model)
        {
            if (model.certificationId != 0)
            {
                var cert = _bd.GetCertification(model.certificationId);
                if (cert != null)
                {
                    _bd.Delete(model.certificationId);
                    return RedirectToAction(nameof(Index));

                }
            }
            return View(model);
        }
    }
}

Controllers/StudentController.cs
using certificationRegister.Models;
using certificationRegister.Repositories;
using certificationRegister.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace certificationRegister.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private readonly IRepository<Student> _bd;
        private readonly IRepository<Certification> _ct;
        private readonly AppDbcontext _app;

        public StudentController(IRepository<Student> bd, IRepository<Certification> ct, AppDbcontext app)
        {
            _bd = bd;
            _ct = ct;
            _app = app;
        }
        public IActionResult Index()
        {
            var students = _bd.AllCertification();
            return View(students);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(StudentCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var std = new Student()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Country = model.Country,
                };
                _bd.Create(std);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id != 0)
            {
                var st = _bd.GetCertification(id);
                if (st != null)
                {
                    var model = new StudentEditViewModel()
                    {
                        studentId = st.studentId,
                        FirstName = st.FirstName,
                        LastName = st.LastName,
                        Country = st.Country,
                    };
                    return View(model);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(StudentEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var st = _bd.GetCertification(model.studentId);
                if (st != null)
                {
                    st.FirstName = model.FirstName;
                    st.LastName = model.LastName;
                    st.Country = model.Country;
                    _bd.Update(st);
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(model);
        }

        //[HttpPost]
        //public IActionResult Changer(StudentChangeStatusViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var st = _bd.GetCertification(model.studentId);
        //        if (st != null)
        //        {
        //            st.status = model.status;
        //            _bd.Update(st);
        //        }
                
        //    }
        //    return RedirectToAction(nameof(Index));
        //}

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var st = _bd.GetCertification(id);
            if (st != null)
            {

                List<StudentAddCertificationViewModel> models = new List<StudentAddCertificationViewModel>();
                var certifications = _ct.AllCertification();
                foreach (Certification cert in certifications)
                {
                    StudentAddCertificationViewModel model = new StudentAddCertificationViewModel()
                    {
                        CertificationId = cert.certificationId,
                        libelle = cert.libelle,
                        sigle = cert.sigle,
                        IsSelected = false
                    };

                    if (IsJoin(model.CertificationId, st.studentId))
                    {
                        model.IsSelected = true;
                    }
                    models.Add(model);
                }
                ViewBag.student = st.FirstName + " " + st.LastName;
                ViewBag.studentId = st.studentId;
                return View(models);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Detail(List<StudentAddCertificationViewModel> model, int studentId)
        {
            var student = await _app.students.Include(s => s.CertificationsLink)
                .SingleAsync(s => s.studentId == studentId);
            if (student != null)
            {
                for (int i = 0; i < model.Count; i++)
                {
                    var cert = await _app.certifications.Include(c => c.StudentsLink)
                        .SingleAsync(c => c.certificationId == model[i].CertificationId);

                    var data = new StudentCertification()
                    {
                        Student = student,
                        Certification = cert,
                        DateCertified = model[i].dte,
                        CertId = model[i].CertificationId,
                        StudId = studentId,
                        IsActive = true
                    };

                    //Detacher la certification a l'etudiant
                    if (IsJoin(model[i].CertificationId, studentId) && !model[i].IsSelected)
                    {
                        //var linkremove = cert.StudentsLink.Where(s => s.StudId == studentId).FirstOrDefault();
                        _app.Remove(data);
                        await _app.SaveChangesAsync();
                    }//Joindre la certification a l'etudiant
                    else if (!IsJoin(model[i].CertificationId, studentId) && model[i].IsSelected)
                    {
                        student.CertificationsLink.Add(data);
                        await _app.SaveChangesAsync();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        private bool IsJoin(int certId, int studId)
        {
            var result = _app.certifications.Where(c => c.certificationId == certId)
                 .Include(c => c.StudentsLink)
                 .Where(c => c.StudentsLink.Any(s => s.StudId == studId))
                 .FirstOrDefault();
            if (result != null)
            {
                return true;
            }
            else
            {
                return false;
            }

        }
    }
}

Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser>  _signInManager
@inject UserManager<AppUser> _userManager

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">
    <!-- Title Page-->
    <title>@ViewBag.Title | GECB</title>

    <!-- Fontfaces CSS-->

    <link href="~/css/font-face.css" rel="stylesheet" />
    <link href="~/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/mdi-font/css/material-design-iconic-font.css" rel="stylesheet" />
    <!-- Bootstrap CSS-->
    <link href="~/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">
    <link href="~/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <!-- Main CSS-->
    <link href="~/css/theme.css" rel="stylesheet" media="all">

</head>
<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER DESKTOP-->
        <header class="header-desktop3 d-none d-lg-block">
            <div class="section__content section__content--p35">
                <div class="header3-wrap">
                    <div class="header__logo">
                        <a href="~/#">
                            <img src="~/images/logo.png" width="150" alt="certification GECB" />
                        </a>
                    </div>
                    @if (_signInManager.IsSignedIn(User))
                    {
                        <div class="header__navbar">
                            <ul class="list-unstyled">
                                <li class="has-sub">
                                    <a href="#">
                                        <i class="fas fa-copy"></i>
                                        <span class="bot-line"></span>Certifications
                                    </a>
                                    <ul class="header3-sub-list list-unstyled">
                                        <li>
                                            <a asp-controller="Certification" asp-action="Index">All Certifications</a>
                                        </li>
                                        <li>
                                            <a asp-controller="Certification" asp-action="Create">Add New Certification</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="has-sub">
                                    <a href="~/#">
                                        <i class="fas fa-users"></i>
                                        <span class="bot-line"></span>Students
                                    </a>
                                    <ul class="header3-sub-list list-unstyled">
                                        <li>
                                            <a asp-controller="Student" asp-action="Index">All Students</a>
                                        </li>
                                        <li>
                                            <a asp-controller="Student" asp-action="Create">Add New Student</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    }
                    @if (_signInManager.IsSignedIn(User))
                    {
                        AppUser user = await _userManager.FindByEmailAsync(User.Identity.Name);
                        <div class="header__tool">
                            <div class="header-button-item js-item-menu">
                                <i class="zmdi zmdi-settings"></i>
                                <div class="setting-dropdown js-dropdown">
                                    <div class="account-dropdown__body">
                                        <div class="account-dropdown__item">
                                            <a asp-controller="Account" asp-action="Register">
                                                <i class="zmdi zmdi-settings"></i>Add Account
                                            </a>
                                        </div>
                                        <div class="account-dropdown__item">
                                            <a href="~/#">
                                                <i class="zmdi zmdi-settings"></i>Setting
                                            </a>
                                        </div>
                                        <div class="account-dropdown__item">
                                            <a href="~/#">
                                                <i class="zmdi zmdi-money-box"></i>Billing
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            
                            <div class="account-wrap">
                                <div class="account-item account-item--style2 clearfix js-item-menu">
                                    <div class="image">
                                        <img src="~/images/icon/avatar-01.jpg" alt="John Doe" />
                                    </div>
                                    <div class="content">
                                        <a class="js-acc-btn" href="~/#">@user.FirstName <span> </span> @user.LastName</a>
                                    </div>
                                    <div class="account-dropdown js-dropdown">
                                        <div class="info clearfix">
                                            <div class="image">
                                                <a href="~/#">
                                                    <img src="~/images/icon/avatar-01.jpg" alt="John Doe" />
                                                </a>
                                            </div>
                                            <div class="content">
                                                <h5 class="name">
                                                    <a href="~/#">@user.FirstName <span> </span> @user.LastName</a>
                                                </h5>
                                                <span class="email">@User.Identity.Name</span>
                                            </div>
                                        </div>
                                        <div class="account-dropdown__body">
                                            <div class="account-dropdown__item">
                                                <a asp-controller="Account" asp-route-id="@user.Id" asp-action="Edit">
                                                    <i class="zmdi zmdi-account"></i>Edit My Account
                                                </a>
                                            </div>
                                            <div class="account-dropdown__item">
                                                <a href="~/#">
                                                    <i class="zmdi zmdi-settings"></i>Setting
                                                </a>
                                            </div>
                                        </div>
                                        <div class="account-dropdown__footer">
                                            <form asp-action="Logout" asp-controller="Account" method="post">
                                                <button type="submit" class="btn btn-danger" style="width:100%">
                                                    <i class="zmdi zmdi-power"></i>Logout
                                                </button>
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>
                    }
                </div>
            </div>
        </header>
        <!-- END HEADER DESKTOP-->
        <!-- PAGE CONTENT-->
        <div class="page-content--bgf7">
            <!-- BREADCRUMB-->
            <section class="au-breadcrumb2">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="au-breadcrumb-content">
                                <div class="au-breadcrumb-left">
                                    <span class="au-breadcrumb-span">You are here:</span>
                                    <ul class="list-unstyled list-inline au-breadcrumb__list">
                                        <li class="list-inline-item active">
                                            <a href="#">Home</a>
                                        </li>
                                        <li class="list-inline-item seprate">
                                            <span>/</span>
                                        </li>
                                        <li class="list-inline-item">@ViewBag.lien</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END BREADCRUMB-->
            @RenderBody()
            <!-- COPYRIGHT-->
            <section class="p-t-60 p-b-20">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="copyright">
                                <p>Copyright © 2022 GECB. All rights reserved. Template by <a href="https://gecb.cm">GECB</a>| <a asp-controller="Account" asp-action="Login">Login</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END COPYRIGHT-->
        </div>
        <!-- Jquery JS-->
        <script src="~/vendor/jquery-3.2.1.min.js"></script>
        <!-- Bootstrap JS-->
        <script src="~/vendor/bootstrap-4.1/popper.min.js"></script>
        <script src="~/vendor/bootstrap-4.1/bootstrap.min.js"></script>
        <!-- Vendor JS       -->
        <script src="~/vendor/slick/slick.min.js">
        </script>
        <script src="~/vendor/wow/wow.min.js"></script>
        <script src="~/vendor/animsition/animsition.min.js"></script>
        <script src="~/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
        </script>
        <script src="~/vendor/counter-up/jquery.waypoints.min.js"></script>
        <script src="~/vendor/counter-up/jquery.counterup.min.js">
        </script>
        <script src="~/vendor/circle-progress/circle-progress.min.js"></script>
        <script src="~/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
        <script src="~/vendor/chartjs/Chart.bundle.min.js"></script>
        <script src="~/vendor/select2/select2.min.js">
        </script>

        <!-- Main JS-->
        <script src="~/js/main.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
        @RenderSection(name: "DataTables", required: false);

</div>
</body>

</html>
<!-- end document-->